local constants = {
    SCHEMA_VERSION = 2,
    CONFIG_SCHEMA_VERSION = 2,
    ADDRESS_BOOK_SCHEMA_VERSION = 2,
    UPDATE_MANIFEST_SCHEMA_VERSION = 1,
    UPDATE_STATE_SCHEMA_VERSION = 1,
    DEFAULT_ADDRESS_BOOK_CACHE_PATH = "/sgc/cache/address_book.lua",
    DEFAULT_ADDRESS_BOOK_SERVER_PATH = "/sgc/data/address_book.lua",
    DEFAULT_UPDATE_MODE = "disabled",
    DEFAULT_UPDATE_BASE_URL = "http://127.0.0.1:8080",
    DEFAULT_UPDATE_CHANNEL = "stable",
    DEFAULT_UPDATE_STATE_PATH = "/sgc/state/update_state.lua",
    DEFAULT_UPDATE_TEMP_DIR = "/sgc/tmp/update",
    DEFAULT_CONFIG_PATHS = {
        "/sgc/config.lua",
        "sgc/config.lua",
        "/config.lua",
        "config.lua",
    },
    ROLE_ORDER = {
        "site_controller",
        "gate_controller",
        "dial_console",
        "veto_console",
        "display",
        "iris_controller",
        "alarm_controller",
        "energy_controller",
        "address_book_server",
        "update_client",
        "bridge",
    },
    ROLE_SET = {
        site_controller = true,
        gate_controller = true,
        dial_console = true,
        veto_console = true,
        display = true,
        iris_controller = true,
        alarm_controller = true,
        energy_controller = true,
        address_book_server = true,
        update_client = true,
        bridge = true,
    },
    APP_MODULES = {
        site_controller = "apps.site_controller",
        gate_controller = "apps.gate_controller",
        dial_console = "apps.dial_console",
        veto_console = "apps.veto_console",
        display = "apps.display",
        iris_controller = "apps.iris_controller",
        alarm_controller = "apps.alarm_controller",
        energy_controller = "apps.energy_controller",
        address_book_server = "apps.address_book_server",
        update_client = "apps.update_client",
        bridge = "apps.bridge",
    },
    ENVELOPE_TYPES = {
        "hello",
        "command",
        "event",
        "state",
        "result",
        "addressbook",
    },
    ENVELOPE_TYPE_SET = {
        hello = true,
        command = true,
        event = true,
        state = true,
        result = true,
        addressbook = true,
    },
    PROTOCOLS = {
        hello = "sgc.hello",
        command = "sgc.command",
        event = "sgc.event",
        state = "sgc.state",
        addressbook = "sgc.addressbook",
        update = "sgc.update",
    },
    PROTOCOL_SET = {
        ["sgc.hello"] = true,
        ["sgc.command"] = true,
        ["sgc.event"] = true,
        ["sgc.state"] = true,
        ["sgc.addressbook"] = true,
        ["sgc.update"] = true,
    },
    ADDRESS_LENGTHS = {
        system = 6,
        stellar = 7,
        galactic = 8,
    },
    INTERFACE_PRIORITY = {
        "advanced_crystal_interface",
        "crystal_interface",
        "basic_interface",
    },
}

return constants
