local constants = {
    SCHEMA_VERSION = 2,
    CONFIG_SCHEMA_VERSION = 2,
    ADDRESS_BOOK_SCHEMA_VERSION = 2,
    UPDATE_MANIFEST_SCHEMA_VERSION = 1,
    UPDATE_STATE_SCHEMA_VERSION = 1,
    DEFAULT_ADDRESS_BOOK_CACHE_PATH = "/sgc/cache/address_book.lua",
    DEFAULT_ADDRESS_BOOK_DEBUG_PATH = "/sgc/tmp/address_book_snapshot.lua",
    DEFAULT_ADDRESS_BOOK_SERVER_PATH = "/sgc/data/address_book.json",
    DEFAULT_UPDATE_MODE = "disabled",
    DEFAULT_UPDATE_BASE_URL = "http://127.0.0.1:8090",
    DEFAULT_UPDATE_CHANNEL = "stable",
    DEFAULT_UPDATE_STATE_PATH = "/sgc/state/update_state.lua",
    DEFAULT_UPDATE_TEMP_DIR = "/sgc/tmp/update",
    DEFAULT_HOST_LIFECYCLE_INTENT_PATH = "/sgc/state/host_lifecycle_intent.lua",
    DEFAULT_DIAL_MODE = "auto",
    DEFAULT_MONITOR_TEXT_SCALE = 1,
    DEFAULT_ALARM_MONITOR_TEXT_SCALE = 0.5,
    DEFAULT_COMMAND_TIMEOUT_SECONDS = 10,
    DEFAULT_DIAL_COMMAND_TIMEOUT_SECONDS = 90,
    DEFAULT_STATUS_COMMAND_TIMEOUT_SECONDS = 3,
    ALARM_PULSE_DURATION_MS = 1000,
    ALARM_SIGNAL_NAMES = {
        "connection_established",
        "connection_incoming",
        "connection_outgoing",
        "dialing",
        "connection_disconnected",
        "traveller_in",
        "traveller_out",
        "wormhole_incoming",
        "wormhole_outgoing",
        "chevron_engaged",
        "message_received",
        "reset",
        "system_error",
    },
    ALARM_SIGNAL_SET = {
        connection_established = true,
        connection_incoming = true,
        connection_outgoing = true,
        dialing = true,
        connection_disconnected = true,
        traveller_in = true,
        traveller_out = true,
        wormhole_incoming = true,
        wormhole_outgoing = true,
        chevron_engaged = true,
        message_received = true,
        reset = true,
        system_error = true,
    },
    GATE_EVENT_SIGNAL_NAMES = {
        "traveller_in",
        "traveller_out",
        "wormhole_incoming",
        "wormhole_outgoing",
        "chevron_engaged",
        "message_received",
        "reset",
    },
    GATE_EVENT_SIGNAL_SET = {
        traveller_in = true,
        traveller_out = true,
        wormhole_incoming = true,
        wormhole_outgoing = true,
        chevron_engaged = true,
        message_received = true,
        reset = true,
    },
    ALARM_OUTPUT_DRIVER_SET = {
        redstone = true,
        bundled = true,
    },
    ALARM_OUTPUT_BINDING_MODE_SET = {
        direct = true,
        pulse = true,
    },
    ALARM_SPEAKER_PATTERN_SET = {
        pattern_alpha = true,
        pattern_beta = true,
    },
    BUNDLED_COLOR_NAMES = {
        "white",
        "orange",
        "magenta",
        "lightBlue",
        "yellow",
        "lime",
        "pink",
        "gray",
        "lightGray",
        "cyan",
        "purple",
        "blue",
        "brown",
        "green",
        "red",
        "black",
    },
    BUNDLED_COLOR_SET = {
        white = true,
        orange = true,
        magenta = true,
        lightBlue = true,
        yellow = true,
        lime = true,
        pink = true,
        gray = true,
        lightGray = true,
        cyan = true,
        purple = true,
        blue = true,
        brown = true,
        green = true,
        red = true,
        black = true,
    },
    BUNDLED_OUTPUT_COLOR_SET = {
        orange = true,
        magenta = true,
        lightBlue = true,
        yellow = true,
        lime = true,
        pink = true,
        gray = true,
        lightGray = true,
        cyan = true,
        purple = true,
        blue = true,
        brown = true,
        green = true,
        red = true,
    },
    DEFAULT_CONFIG_PATHS = {
        "/sgc/config.lua",
        "sgc/config.lua",
        "/config.lua",
        "config.lua",
    },
    ROLE_ORDER = {
        "site_controller",
        "gate_controller",
        "dial_console",
        "veto_console",
        "display",
        "iris_controller",
        "alarm_controller",
        "energy_controller",
        "address_book",
        "update_client",
        "bridge",
    },
    HOST_LIFECYCLE_ROLE_ORDER = {
        "site_controller",
        "gate_controller",
        "dial_console",
        "alarm_controller",
        "address_book_server",
        "address_book",
    },
    ROLE_SET = {
        site_controller = true,
        gate_controller = true,
        dial_console = true,
        veto_console = true,
        display = true,
        iris_controller = true,
        alarm_controller = true,
        energy_controller = true,
        address_book = true,
        address_book_server = true,
        update_client = true,
        bridge = true,
    },
    APP_MODULES = {
        site_controller = "apps.site_controller",
        gate_controller = "apps.gate_controller",
        dial_console = "apps.dial_console",
        veto_console = "apps.veto_console",
        display = "apps.display",
        iris_controller = "apps.iris_controller",
        alarm_controller = "apps.alarm_controller",
        energy_controller = "apps.energy_controller",
        address_book = "apps.address_book_server",
        address_book_server = "apps.address_book_server",
        update_client = "apps.update_client",
        bridge = "apps.bridge",
    },
    ENVELOPE_TYPES = {
        "hello",
        "command",
        "event",
        "state",
        "result",
        "addressbook",
    },
    ENVELOPE_TYPE_SET = {
        hello = true,
        command = true,
        event = true,
        state = true,
        result = true,
        addressbook = true,
    },
    PROTOCOLS = {
        hello = "sgc.hello",
        command = "sgc.command",
        event = "sgc.event",
        state = "sgc.state",
        addressbook = "sgc.addressbook",
        update = "sgc.update",
    },
    PROTOCOL_SET = {
        ["sgc.hello"] = true,
        ["sgc.command"] = true,
        ["sgc.event"] = true,
        ["sgc.state"] = true,
        ["sgc.addressbook"] = true,
        ["sgc.update"] = true,
    },
    ADDRESS_LENGTHS = {
        system = 6,
        stellar = 7,
        galactic = 8,
    },
    POINT_OF_ORIGIN_SYMBOL = 0,
    DIAL_MODE_SET = {
        auto = true,
        fast = true,
        medium = true,
        slow = true,
    },
    INTERFACE_PRIORITY = {
        "advanced_crystal_interface",
        "crystal_interface",
        "basic_interface",
    },
}

return constants
